ottogether/src/App.tsx
최상위 컴포넌트 App.tsx의 뼈대를 만들었습니다.
App.tsx 파일 생성과 Header, Footer, RouterProvider의 기본 컴포넌트 삽입 후 주석처리
기본적인 컴포넌트만 넣어놓은 상태인데 추가적으로 필요한 컴포넌트나 수정할 부분 알려주세요
=> FEAT : App.tsx

ottogether/src/components/movieCard/MovieCard.module.css, ottogether/src/components/movieCard/MovieCard.tsx, ottogether/src/components/movieCard/MovieList.module.css, ottogether/src/components/movieCard/MovieList.tsx, ottogether/src/components/movieCard/SectionGroup.tsx, ottogether/src/lib/data.ts, ottogether/src/pages/Home/Home.tsx, ottogether/src/supabase/supabase.type.ts, ottogether/src/tmdbApi/fetchGenres.ts, ottogether/src/tmdbApi/fetchMoviesByGenre.ts, ottogether/src/tmdbApi/fetchPopular.ts, ottogether/src/tmdbApi/getMovieDetail.ts, ottogether/src/tmdbApi/getMovieProvider.ts, ottogether/src/tmdbApi/index.ts, ottogether/src/tmdbApi/movie.type.ts, ottogether/src/util/toggleFavoriteMovie.ts
=> feature/api tmdb 함수, 홈페이지

ottogether/src/pages/Register/RegisterProfile.tsx
RegisterProfile Skip Button 클릭 시 랜덤 프로필/헤더를 저장하도록 수정
> Issue #66 
- RegisterProfile Skip Button 클릭 시 랜덤 프로필/헤더를 저장하도록 수정
=> feat : RegisterProfile Skip Button 클릭 시 랜덤 프로필/헤더를 저장하도록 수정 (#66)

ottogether/src/components/member/MemberCard.tsx, ottogether/src/components/reviewCard/ReviewCreate.module.css, ottogether/src/components/reviewCard/ReviewCreate.tsx, ottogether/src/components/reviewCard/SupaData.ts, ottogether/src/components/reviewCard/supabase.type.ts, ottogether/src/pages/Review_/Review.tsx
ReviewCard를 생성하는 editor 기능 구현
ReviewCard를 생성하는 input 창 생성 후 데이터 입력받아서 db에 업데이트
=> ReviewCreate 기능 80% 구현

ottogether/src/components/reviewDetailPopup/ReviewDetailPopup.module.css, ottogether/src/components/reviewDetailPopup/reviewDetailPopup.tsx, ottogether/src/pages/Members/Members.tsx
댓글 수정 버튼을 만들고 기능 구현
수정 버튼을 누르면 기존 데이터를 열고 수정 가능한 UI를 생성한다. 그리고 수정하면 update로 DB의 데이터를 수정한다.
=> feat : 댓글 수정 기능 구현

ottogether/src/layout/Header.module.css
header 너비 변경
아주 사소하게 거슬리는 문제 하나를 고쳤습니다..
=> style : header 너비 변경

ottogether/src/components/Quotes/QuoteCard.tsx, ottogether/src/components/Search/SearchQuote.module.css, ottogether/src/components/Search/SearchQuote.tsx, ottogether/src/components/Search/SearchTab.module.css, ottogether/src/components/Search/SearchTab.tsx, ottogether/src/pages/Home/Home.tsx, ottogether/src/pages/Quotes/QuotesPage.tsx, ottogether/src/supabase/quotes/searchQuotes.ts, ottogether/src/supabase/supabase.type.ts
Quote 검색 컴포넌트 추가
SearchResult 페이지
- Quote Content 를 검색하여 일치하는 키워드가 들어간 Quote List 출력
QuoteCard & QuoteList 수정
- QuoteCard 에 타입 방어 추가 (quote가 Prop으로 안떨어지면 null 출력)
- Quotes_like 에는 user_id, quote_id 가 모두 일치하는 데이터가 없을 수도 있으니 maybeSingle()로 변경
- QuoteCard Prop으로 Quote 전체를 받고 내부에서 구조분해할당하도록 변경
- QuoteCard 재사용성 증가를 위해 className을 추가로 받을 수 있도록 수정
기타 작업 내용 
- Home 의 Ott Toggle List에서 선택 항목이 보이도록 onToggle 함수 수정
@JinKeyP 진강님 QuoteCard랑 QuoteList 수정한 거 있는데 혹시 충돌 나는지 봐주세요~
=> [Feature/search] Quote 검색 컴포넌트 추가

ottogether/src/lib/movieDetailType.ts, ottogether/src/pages/ContentsDetail/ContentsDetail.tsx
contentsDetail 페이지 기본 구조 제작
contentsDetail 페이지 기본 구조 제작
=> feat : contentsDetail 페이지 제작중

ottogether/src/layout/Header.module.css, ottogether/src/layout/Header.tsx
Header 아이콘 사이즈 조정, 페이지 이동 시 햄버거 메뉴 닫히도록 수정
> Issue #112 
- Header의 검색 아이콘 사이즈를 줄이고, Notification 아이콘 사이즈 키움
- 모바일 화면에서 Nav 이동 시 햄버거 메뉴 닫히도록 수정
- Logout 이후 로그아웃 되었다는 알림 추가
=> Feature/header Header 아이콘 사이즈 조정, 페이지 이동 시 햄버거 메뉴 닫히도록 수정

ottogether/src/pages/Members/Members.module.css, ottogether/src/pages/Members/Members.tsx
Member Page CSS 스타일 수정
- 페이지 레이아웃 깨지지 않도록 container 추가 & height 부여
=> style : Member Page CSS 스타일 수정 (#111)

ottogether/src/components/member/MemberCard.tsx, ottogether/src/pages/Members/Members.tsx, ottogether/src/pages/Register/RegisterDetail.tsx, ottogether/src/supabase/supabase.type.ts
회원가입 시 알림 설정 정보를 저장할 수 있는 함수 추가
> Closes #113 
- Register 과정에서 notification_setting 테이블에 설정 정보를 전부 true로 넣는 형태로 저장
- created_at 컬럼을 추가하고, 이후 수정 시 updated_at을 변경할 수 있도록 테이블 구조 수정
@cheezstick 저는 데이터 잘 들어오는 것 같은데 한 번 확인해보셔요!
=> feat : 회원가입 시 알림 설정 정보를 저장할 수 있는 함수 추가 (#113)

ottogether/src/components/reviewCard/ReviewCard.module.css, ottogether/src/components/reviewCard/ReviewCard.tsx, ottogether/src/components/reviewCard/StarRating.tsx, ottogether/src/components/reviewDetailPopup/reviewDetailPopup.tsx, ottogether/src/pages/Members/Members.tsx, ottogether/src/pages/MovieDetail/MovieDetail.module.css, ottogether/src/pages/MovieDetail/MovieDetail.tsx, ottogether/src/pages/Review_/Review.tsx, ottogether/src/supabase/supabase.type.ts, ottogether/src/tmdbApi/getContentDetail.ts, ottogether/src/tmdbApi/series.type.ts
contentsDetailPage 관련 코드 수정 및 새로운 기능 추가
- 디테일 페이지에 명대사 카드를 출력하도록 구현
- reviewCard 너비 반응형으로 바꿔서 다른 페이지에서 호환되도록 수정
- review 페이지에서 발생하는 에러 수정
=> feat : contentsDetailPage에 명대사 카드 출력기능 + reviewCard 구조 수정

ottogether/src/pages/MovieDetail/MovieDetail.tsx, ottogether/src/supabase/supabase.type.ts
supabase.type 수정으로 발생한 코드 수정
- supabase.type 수정으로 발생한 코드 수정
=> fix : type error 수정

ottogether/src/components/Quotes/QuoteCard.tsx, ottogether/src/layout/Header.tsx, ottogether/src/supabase/storage/uploadImage.ts, ottogether/src/supabase/supabase.type.ts
type 에러나 변수 에러 뜨는 파일들 수정
- uploadImage 에서 사용하지 않는 변수 삭제
- header notification에서 setNotification 함수 임시 추가
- QuoteCard 에서 merge 중 사라진 변경 사항 다시 추가
- 사용하지 않는 변수 이름 삭제
=> Feature/error 에러 뜨는 내역 수정

ottogether/src/components/Search/SearchUser.tsx, ottogether/src/supabase/profile/searchUserProfile.ts
SearchUser -> UserCard Props 변경
- SearchUser 컴포넌트에서 UserCard에 넘겨주는 Props를 review_like, quotes_like 에서 review, quotes로 변경
=> fix : SearchUser -> UserCard Props 변경

ottogether/src/components/reviewCard/ReviewCard.module.css, ottogether/src/components/reviewCard/ReviewCard.tsx, ottogether/src/components/reviewDetailPopup/reviewDetailPopup.tsx, ottogether/src/pages/Review_/Review.tsx
reviewCard 에러 핸들링 + 크기 조정
- reviewCard에서 제대로 댓글 수가 표시되지 않았던 에러 수정
- reviewCard의 크기가 제대로 설정되지 않았던 에러 수정
=> fix : reviewCard 크기 조정 및 댓글 수 작성 로직 수정

ottogether/src/components/member/MemberCard.module.css, ottogether/src/pages/Home/Home.tsx, ottogether/src/pages/Members/Members.module.css
Members 페이지 CSS 재조정
Members 페이지 height나 width값 재조정
=> style : Members 페이지 CSS 재조정

ottogether/src/pages/Review_/Review.tsx
fix : 파일 경로 대/소문자 수정
fix : 파일 경로 대/소문자 수정
=> fix : 파일 경로 대/소문자 수정

ottogether/netlify.toml
test : netlify test
test : netlify 배포 test 용 파일 생성
=> test : netlify test

netlify.toml, ottogether/src/components/reviewDetailPopup/ReviewDetailPopup.module.css
자잘한 에러 수정 + Netlify test
자잘한 에러 수정 + Netlify test
=> Feature/error 자잘한 에러 수정 + Netlify test

ottogether/src/components/reviewCard/ReviewCard.tsx, ottogether/src/pages/MovieDetail/MovieDetail.module.css, ottogether/src/pages/MovieDetail/MovieDetail.tsx, ottogether/src/pages/Review_/Review.tsx
- contents Detail Page에서 Review Section 구현하기
- Review Section에 reviewCard 불러오도록 추가
-  Review Card를 가져오긴 했는데, 너무 디자인적으로 별로여서 컴포넌트를 새로 만들까 생각중입니다.
=> feat : 디테일 페이지에 리뷰 출력 구현(임시)

ottogether/src/components/Notifications/Notifications.module.css, ottogether/src/components/Notifications/Notifications.tsx, ottogether/src/components/inMyPage/LikedReviews.tsx, ottogether/src/components/inMyPage/MyPageVideos.module.css, ottogether/src/components/inMyPage/MySettings/NotificationSection.tsx, ottogether/src/components/inMyPage/ProfileBox.module.css, ottogether/src/components/inMyPage/ProfileBox.tsx, ottogether/src/pages/MyPage/MyPage.tsx, ottogether/src/util/createNotifications.ts
MyPage Notification Settings 기능 구현 #39 
사용자가 설정한 내용에 따라 알림을 구분하여 받습니다.
=> feat : MyPage - Notification 기능 구현

ottogether/src/components/movieCard/MovieList.tsx
fix : Home에서 양옆 화살표 아이콘 깨지는 것 수정
상대경로 import 로 변경
=> fix : Home에서 양옆 화살표 아이콘 깨지는 것 수정

ottogether/public/emptyThumbsUp.svg, ottogether/src/components/reviewCard/SmallReviewCard/SmallReviewCard.module.css, ottogether/src/components/reviewCard/SmallReviewCard/SmallReviewCard.tsx, ottogether/src/components/reviewDetailPopup/reviewDetailPopup.tsx, ottogether/src/pages/MovieDetail/MovieDetail.module.css, ottogether/src/pages/MovieDetail/MovieDetail.tsx, ottogether/src/pages/Review_/Review.tsx
소형 reviewCard 제작 + 디테일 페이지 내부에서 좋아요 기능 활성화
- contents Detail Page에서 표시할 전용 ReviewCard 제작
- review Detail Page에서 좋아요 버튼 상호작용 가능하도록 기능 활성화
=> feat : 소형 reviewCard 제작 + 디테일 페이지 내부에서 좋아요 기능 활성화

ottogether/src/components/Quotes/QuoteCard.tsx
=> feature/quotescard 명대사 클릭시 페이지이동

ottogether/src/components/member/MemberCard.module.css, ottogether/src/components/member/MemberCard.tsx, ottogether/src/components/reviewCard/ReviewCard.tsx, ottogether/src/components/reviewDetailPopup/reviewDetailPopup.tsx, ottogether/src/pages/MovieDetail/MovieDetail.tsx
contentsDetail와 ~Card 컴포넌트를 수정했습니다.
- contentsDetailPage의 favorite 버튼 클릭 시 member Component를 업데이트
- memberCard의 디자인 수정
- reviewCard에서 좋아요 취소 로직이 제대로 동작하지 않던 문제 수정
=> contentsDetail 및 Card 컴포넌트 수정

ottogether/src/components/Quotes/QuoteCard.module.css, ottogether/src/components/Quotes/QuoteCard.tsx, ottogether/src/components/inMyPage/MySettings/ProfileSettings.module.css, ottogether/src/components/inMyPage/MySettings/ProfileSettings.tsx, ottogether/src/components/inMyPage/ProfileBox.module.css, ottogether/src/components/inMyPage/ProfileBox.tsx, ottogether/src/components/member/MemberCard.module.css, ottogether/src/components/member/MemberCard.tsx, ottogether/src/components/movieCard/MovieCard.tsx, ottogether/src/components/reviewCard/ReviewCard.module.css, ottogether/src/components/reviewCard/ReviewCard.tsx, ottogether/src/components/reviewCard/ReviewCreate.module.css, ottogether/src/components/reviewCard/ReviewCreate.tsx, ottogether/src/components/reviewCard/SmallReviewCard/SmallReviewCard.module.css, ottogether/src/components/reviewCard/SmallReviewCard/SmallReviewCard.tsx, ottogether/src/components/reviewDetailPopup/ReviewDetailPopup.module.css, ottogether/src/components/reviewDetailPopup/reviewDetailPopup.tsx, ottogether/src/pages/ContentsDetail/ContentsDetail.tsx, ottogether/src/pages/Home/Home.tsx, ottogether/src/pages/MovieDetail/MovieDetail.tsx, ottogether/src/pages/MyPage/MyPage.module.css, ottogether/src/pages/NotFound/NotFound.module.css, ottogether/src/pages/Review_/Review.tsx, ottogether/src/router/routes.ts, ottogether/src/supabase/notifications/useNotifications.ts, ottogether/src/util/getQuote.ts, ottogether/vercel.json
=> Feature/error QA하면서 발견한 수정

ottogether/src/components/reviewCard/ReviewCard.tsx, ottogether/src/components/reviewCard/SmallReviewCard/SmallReviewCard.tsx, ottogether/src/components/reviewDetailPopup/ReviewDetailPopup.module.css, ottogether/src/pages/MovieDetail/MovieDetail.tsx, ottogether/src/pages/Review_/Review.tsx
contentsDetailPage에서 review Card를 클릭했을 때 상호작용 추가
- Read More 클릭 시 ReviewPage로 navigate
- navigate 후 동일한 Card가 있는 위치로 스크롤
=> feat : contentsDetailPage에서 review Card를 클릭했을 때 상호작용 추가

ottogether/src/components/reviewDetailPopup/reviewDetailPopup.tsx, ottogether/src/pages/MovieDetail/MovieDetail.tsx, ottogether/src/pages/MovieDetail/MovieLoading/MovieLoading.module.css, ottogether/src/pages/MovieDetail/MovieLoading/MovieLoading.tsx, ottogether/src/pages/Review_/Review.tsx
contents Detail Page 로딩 중 애니메이션 추가
contents Detail Page 로딩 중 애니메이션 추가
=> Feature/contentsDetailPage 로딩 애니메이션 추가

ottogether/src/components/inMyPage/CreatedReviews.tsx, ottogether/src/components/inMyPage/LikedReviews.tsx, ottogether/src/pages/Review_/Review.tsx
MyPage 리뷰 관련 오류 수정
MyPage 에서 리뷰를 클릭할 때 모달이 꼬이거나 좋아요를 눌렀을 때 모달이 뜨는 오류 수정
=> fix : MyPage - 리뷰 모달 관련 오류 수정

ottogether/src/components/Quotes/QuoteCreate.tsx, ottogether/src/pages/Quotes/QuotesPage.tsx, ottogether/src/supabase/supabase.type.ts
quotes insert 시 mediaType 옵션 추가
- quotes insert 시 mediaType 옵션 추가
- supabase db quote table에 mediaType column 추가
=> feat : quotes insert 시 mediaType 옵션 추가

ottogether/src/pages/MovieDetail/MovieDetail.tsx
contentsDetailPage에서 명대사와 리뷰 mediaType에 맞춰서 불러오기
contentsDetailPage에서 명대사와 리뷰 mediaType에 맞춰서 불러오기
=> fix : contentsDetailPage에서 명대사와 리뷰 mediaType에 맞춰서 불러오기

ottogether/src/pages/Review_/Review.tsx
feat : contentsDetailPage에서 넘어오고 난 뒤, 해쉬값 삭제
- contentsDetailPage에서 넘어오고 난 뒤, 해쉬값 삭제
=> feat : contentsDetailPage에서 넘어오고 난 뒤, 해쉬값 삭제

ottogether/src/components/FindPassword/FindPassword.tsx
fix : Login 비밀번호 변경 메일 주소 수정
fix : Login 비밀번호 변경 메일 주소 수정
=> fix : Login 비밀번호 변경 메일 주소 수정

ottogether/src/components/Quotes/QuoteCard.tsx, ottogether/src/pages/Quotes/QuotesPage.tsx
QuoteCard 삭제 시 mediaType 옵션 넣기 + QuotePage에서 데이터 렌더링 방식 수정
- QuoteCard 삭제 시 mediaType 옵션 넣기
- QuotePage에서 데이터 렌더링 방식 수정
=> feat : QuoteCard 삭제 시 mediaType 옵션 넣기 + QuotePage에서 데이터 렌더링 방식 수정
